# **MACRO ANALYSIS AND OPPORTUNITIES FOR LIFESCIENCE INDUSTRY EUROPE**

# 1. DATA EXTRACTION

The following work was made to analyze the opportunities in the European Market for companies in the Medtech.

**Source of Information**:

1) Company Reports: We get the financial reports of the company for the last three years.
2) CORDIS - EU research projects under HORIZON EUROPE (2021 - 2027)
3) Clinical Trias Information from *"https://clinicaltrials.gov/api/v2/studies"*

## 1. CORDIS - EU RESEARCH PROJECTS UNDER HORIZON EUROPE

### Libraries

In [62]:
import sys
!{sys.executable} -m pip install openpyxl
import zipfile
import requests
import urllib.request
import pandas as pd
from pathlib import Path
import os
import re
os.getcwd()

Requirement already satisfied: openpyxl in /Users/fernandacladeramelgar/Documents/2_Projects/TECAN_Application/venv/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/fernandacladeramelgar/Documents/2_Projects/TECAN_Application/venv/lib/python3.13/site-packages (from openpyxl) (2.0.0)

'/Users/fernandacladeramelgar/Documents/2_Projects/TECAN_Application/SalesAnalytics/Scripts'

### 2014 - 2020 Dataset

In [63]:
#url_2014_2020="https://cordis.europa.eu/data/cordis-h2020projects-xlsx.zip"
reports_dir= Path("data/Reports")
#reports_dir.mkdir(parents=True, exist_ok=True)
#zip_path = reports_dir / "cordis-h2020projects-xlsx.zip"
#urllib.request.urlretrieve(url_2014_2020, zip_path)
#with zipfile.ZipFile(zip_path, 'r') as z:
#    z.extract("project.xlsx",reports_dir)
#    z.extract("organization.xlsx",reports_dir)
    
#(reports_dir / "project.xlsx").rename(reports_dir/"project_2014_2020.xlsx")
#(reports_dir / "organization.xlsx").rename(reports_dir/"organization_2014_2020.xlsx")

In [64]:
df_eu_org_14_20 = pd.read_excel(reports_dir / "organization_2014_2020.xlsx", engine="openpyxl")
df_eu_proj_14_20 = pd.read_excel(reports_dir / "project_2014_2020.xlsx", engine="openpyxl")

/Users/fernandacladeramelgar/Documents/2_Projects/TECAN_Application/venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/fernandacladeramelgar/Documents/2_Projects/TECAN_Application/venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

### 2021 - 2027 Dataset

In [65]:
#url_2021_2027="https://cordis.europa.eu/data/cordis-HORIZONprojects-xlsx.zip"
reports_dir= Path("data/Reports")
#reports_dir.mkdir(parents=True, exist_ok=True)
#zip_path = reports_dir / "cordis-HORIZONprojects-xlsx.zip"
#with zipfile.ZipFile(zip_path, 'r') as z:
#urllib.request.urlretrieve(url_2021_2027, zip_path)
#    z.extract("project.xlsx",reports_dir)
#    z.extract("organization.xlsx",reports_dir)
    
#(reports_dir / "project.xlsx").rename(reports_dir/"project_2021_2027.xlsx")
#(reports_dir / "organization.xlsx").rename(reports_dir/"organization_2021_2027.xlsx")

In [66]:
df_eu_org_21_27=pd.read_excel(reports_dir/"organization_2021_2027.xlsx", engine='openpyxl')
df_eu_proj_21_27=pd.read_excel(reports_dir/"project_2021_2027.xlsx", engine='openpyxl')

/Users/fernandacladeramelgar/Documents/2_Projects/TECAN_Application/venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/Users/fernandacladeramelgar/Documents/2_Projects/TECAN_Application/venv/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

### Understanding the Data Structure

In [67]:
df_eu_org_14_20.head()

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,632927,ERC-EuropePMC-1-2014,999905974,GB744495211,THE WELLCOME TRUST LIMITED,NaN,False,PRC,EUSTON ROAD 215 GIBBS BUILDING,NW1 2BE,...,https://ec.europa.eu/info/funding-tenders/oppo...,2018-07-19 09:17:05,2114706,1.0,coordinator,230000,230000,230000,False,NaN
1,633002,ERCSC-VPRES-SUP2014,998221957,CHE105833232MWST,LUDWIG INSTITUT FUR KREBSFORSCHUNG AG,LICR,False,REC,STADELHOFERSTRASSE 22,8001,...,https://ec.europa.eu/info/funding-tenders/oppo...,2018-07-19 09:17:05,2124376,1.0,coordinator,258500,258500,258500,False,NaN
2,633053,EUROfusion,999480726,FR68440546018,INSTITUT DE RADIOPROTECTION ET DE SURETE NUCLE...,IRSN,False,REC,AV DE LA DIVISION LECLERC 31,92260,...,https://ec.europa.eu/info/funding-tenders/oppo...,2017-09-11 10:25:16,1906591,11.0,thirdParty,0,"225986,71","410884,93",False,NaN
3,633053,EUROfusion,999864264,FR15199115684,ECOLE POLYTECHNIQUE,EP,False,HES,ROUTE DE SACLAY,91128,...,https://ec.europa.eu/info/funding-tenders/oppo...,2017-09-11 10:25:16,1912905,11.0,thirdParty,0,"143596,65","261084,83",False,NaN
4,633053,EUROfusion,999547074,FR45180089047,INSTITUT NATIONAL DE RECHERCHE EN INFORMATIQUE...,INRIA,False,REC,DOMAINE DE VOLUCEAU ROCQUENCOURT,78153,...,https://ec.europa.eu/info/funding-tenders/oppo...,2017-09-11 10:25:16,1906120,11.0,thirdParty,0,"817611,23","1486565,88",False,NaN

In [68]:
df_eu_org_21_27.head()

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,101069359,SolDAC,912743326,ESB98896137,LOMARTOV SL,LOMARTOV APPLIED INNOVATION ENGINEERING,True,PRC,CALLE ALFARERIA 3,46100,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,3146679,2,participant,299250,299250,299250,False,NaN
1,101069359,SolDAC,898206033,BE0746474089,EUROPEAN INNOVATION MARKETPLACE ASBL,NaN,False,REC,TRIERSTRAAT 49 STRATENPLAN BUS 7,1040,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1965819,6,participant,149125,149125,149125,False,NaN
2,101069359,SolDAC,928228018,ESB66340514,"COMET GLOBAL INNOVATION, SL",COMET,True,PRC,"C GRAN DE GRACIA NUM 1, PLANTA 4, PUERTA 3",08012,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1947059,1,coordinator,451500,451500,451500,False,NaN
3,101069359,SolDAC,999984253,GB607606448,THE UNIVERSITY COURT OF THE UNIVERSITY OF ST A...,USTAN,False,HES,NORTH STREET 66 COLLEGE GATE,KY16 9AJ,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1906637,8,associatedPartner,NaN,0,0,False,NaN
4,101069359,SolDAC,996435993,ESG64946387,FUNDACIO INSTITUT DE RECERCA EN ENERGIA DE CAT...,IREC-CERCA,False,REC,C/ JARDINS DE LES DONES DE NEGRE 1,08930,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1913642,3,participant,"399593,75","399593,75","399593,75",False,NaN

In [69]:
df_eu_proj_14_20.head()

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,topics,ecSignatureDate,...,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords,Human-validated,legalBasis,Unnamed: 21
0,632927,ERC-EuropePMC-1-2014,CLOSED,Support towards the Europe PMC initiative-Cont...,2014-01-01,2016-03-31,230000,230000,ERC,2014-07-17,...,H2020-Adhoc-2014-20,CSA,"""The proposed action will provide continued su...",2018-07-19 09:17:05,193157,10.3030/632927,"Open Access, Europe PMC, repository, OA",NaN,H2020-EU.1.1.,NaN
1,633002,ERCSC-VPRES-SUP2014,CLOSED,Support to the Vice-Presidents of the ERC Scie...,2014-01-01,2014-12-31,258500,258500,ERC,2014-07-10,...,H2020-Adhoc-2014-20,CSA,The proposed Action will provide the necessary...,2018-07-19 09:17:05,193158,10.3030/633002,ERC Scientific Council,NaN,H2020-EU.1.1.,NaN
2,633053,EUROfusion,SIGNED,Implementation of activities described in the ...,2014-01-01,2022-12-31,"1329689211,5",678800000,EURATOM,2014-09-30,...,EURATOM-Adhoc-2014-20,COFUND-EJP,A Roadmap to the realization of fusion energy ...,2017-09-11 10:25:16,193159,10.3030/633053,false,H2020-Euratom,NaN,NaN
3,633080,MACC-III,CLOSED,Monitoring Atmospheric Composition and Climate...,2014-08-01,2015-08-31,5000000,5000000,SPACE,2014-08-05,...,H2020-Adhoc-2014-20,CSA,MACC-III is the last of the pre-operational st...,2022-08-16 16:46:44,193160,10.3030/633080,false,H2020-EU.2.1.6.,NaN,NaN
4,633085,MyOcean FO,CLOSED,Pre-Operational Marine Service Continuity in T...,2014-10-01,2015-05-31,"6000000,04",6000000,SPACE,2014-10-07,...,H2020-Adhoc-2014-20,CSA,The main objective of the MyOcean Follow On pr...,2022-08-16 16:46:44,193161,10.3030/633085,false,H2020-EU.2.1.6.,NaN,NaN

In [70]:
df_eu_proj_21_27.head()

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,topics,ecSignatureDate,...,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords,Human-validated,legalBasis
0,101069359,SolDAC,SIGNED,Full spectrum SOLar Direct Air Capture & conve...,2022-09-01,2025-08-31,"2073781,25","2073781,25",HORIZON-CL5-2021-D2-01-11,2022-05-12,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-RIA,Ethylene is the chemical industry’s primary bu...,2026-03-27 15:10:23,237915,10.3030/101069359,"zero-carbon, solar energy, air mining, Negativ...",true,HORIZON.2.5
1,101069357,Photo2Fuel,SIGNED,Artificial PHOTOsynthesis to produce FUELs and...,2022-09-01,2025-08-31,"2493171,25",2493171,HORIZON-CL5-2021-D2-01-08,2022-05-18,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-RIA,The Photo2Fuel project will develop a breakthr...,2026-02-12 19:21:26,237916,10.3030/101069357,solar energy; bacteria; archaea; solar fuels; ...,true,HORIZON.2.5
2,101069586,BOLSTER,SIGNED,Bridging Organizations and marginalized commun...,2022-09-01,2025-08-31,3792955,3792955,HORIZON-CL5-2021-D2-01-12,2022-06-10,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-RIA,No European should be put at a disadvantaged b...,2025-09-30 15:22:06,237917,10.3030/101069586,"Transition strategies, Participation, Margin...",true,HORIZON.2.5
3,101069604,GREENET,SIGNED,NCPS NETwork for the GREEN transition in clima...,2022-07-01,2027-12-31,"3250901,25","3250901,25",HORIZON-CL5-2021-D2-01-15,2022-06-09,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-CSA,The overall aim of GREENET is to improve the p...,2026-05-03 20:09:37,237918,10.3030/101069604,"Competence development, Capacity building, CL5...",NaN,HORIZON.2.5
4,101069529,SSH CENTRE,SIGNED,"Social Sciences and Humanities for Climate, En...",2022-09-01,2026-02-28,"2305696,25",2305696,HORIZON-CL5-2021-D2-01-13,2022-05-20,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-CSA,"The Social Sciences & Humanities for Climate, ...",2026-04-15 15:27:43,237919,10.3030/101069529,Transitions; Transdisciplinary; Epistemic cult...,true,HORIZON.2.5

In [71]:
df_eu_org_14_20.columns

Index(['projectID', 'projectAcronym', 'organisationID', 'vatNumber', 'name',
       'shortName', 'SME', 'activityType', 'street', 'postCode', 'city',
       'country', 'nutsCode', 'geolocation', 'organizationURL', 'contactForm',
       'contentUpdateDate', 'rcn', 'order', 'role', 'ecContribution',
       'netEcContribution', 'totalCost', 'endOfParticipation', 'active'],
      dtype='str')

In [72]:
df_eu_org_21_27.columns

Index(['projectID', 'projectAcronym', 'organisationID', 'vatNumber', 'name',
       'shortName', 'SME', 'activityType', 'street', 'postCode', 'city',
       'country', 'nutsCode', 'geolocation', 'organizationURL', 'contactForm',
       'contentUpdateDate', 'rcn', 'order', 'role', 'ecContribution',
       'netEcContribution', 'totalCost', 'endOfParticipation', 'active'],
      dtype='str')

In [73]:
common_eu_org_cols=set(df_eu_org_14_20.columns).intersection(set(df_eu_org_21_27.columns))
common_eu_org_cols

{'SME',
 'active',
 'activityType',
 'city',
 'contactForm',
 'contentUpdateDate',
 'country',
 'ecContribution',
 'endOfParticipation',
 'geolocation',
 'name',
 'netEcContribution',
 'nutsCode',
 'order',
 'organisationID',
 'organizationURL',
 'postCode',
 'projectAcronym',
 'projectID',
 'rcn',
 'role',
 'shortName',
 'street',
 'totalCost',
 'vatNumber'}

In [74]:
df_eu_proj_14_20.columns

Index(['id', 'acronym', 'status', 'title', 'startDate', 'endDate', 'totalCost',
       'ecMaxContribution', 'topics', 'ecSignatureDate', 'frameworkProgramme',
       'masterCall', 'subCall', 'fundingScheme', 'objective',
       'contentUpdateDate', 'rcn', 'grantDoi', 'keywords', 'Human-validated',
       'legalBasis', 'Unnamed: 21'],
      dtype='str')

In [75]:
df_eu_proj_21_27.columns

Index(['id', 'acronym', 'status', 'title', 'startDate', 'endDate', 'totalCost',
       'ecMaxContribution', 'topics', 'ecSignatureDate', 'frameworkProgramme',
       'masterCall', 'subCall', 'fundingScheme', 'objective',
       'contentUpdateDate', 'rcn', 'grantDoi', 'keywords', 'Human-validated',
       'legalBasis'],
      dtype='str')

In [76]:
common_eu_proj_cols=set(df_eu_proj_14_20.columns).intersection(set(df_eu_proj_21_27.columns))
common_eu_proj_cols

{'Human-validated',
 'acronym',
 'contentUpdateDate',
 'ecMaxContribution',
 'ecSignatureDate',
 'endDate',
 'frameworkProgramme',
 'fundingScheme',
 'grantDoi',
 'id',
 'keywords',
 'legalBasis',
 'masterCall',
 'objective',
 'rcn',
 'startDate',
 'status',
 'subCall',
 'title',
 'topics',
 'totalCost'}

In [77]:
df_eu_proj_14_20.rename(columns={'id':'projectID'}, inplace=True)
df_eu_proj_14_20.columns

Index(['projectID', 'acronym', 'status', 'title', 'startDate', 'endDate',
       'totalCost', 'ecMaxContribution', 'topics', 'ecSignatureDate',
       'frameworkProgramme', 'masterCall', 'subCall', 'fundingScheme',
       'objective', 'contentUpdateDate', 'rcn', 'grantDoi', 'keywords',
       'Human-validated', 'legalBasis', 'Unnamed: 21'],
      dtype='str')

In [78]:
df_eu_proj_21_27.rename(columns={'id':'projectID'}, inplace=True)
df_eu_proj_21_27.columns

Index(['projectID', 'acronym', 'status', 'title', 'startDate', 'endDate',
       'totalCost', 'ecMaxContribution', 'topics', 'ecSignatureDate',
       'frameworkProgramme', 'masterCall', 'subCall', 'fundingScheme',
       'objective', 'contentUpdateDate', 'rcn', 'grantDoi', 'keywords',
       'Human-validated', 'legalBasis'],
      dtype='str')

In [79]:
common_cols=set(df_eu_proj_14_20.columns).intersection(set(df_eu_org_14_20.columns))
common_cols

{'contentUpdateDate', 'projectID', 'rcn', 'totalCost'}

In [80]:
common_cols=set(df_eu_proj_21_27.columns).intersection(set(df_eu_org_21_27.columns))
common_cols

{'contentUpdateDate', 'projectID', 'rcn', 'totalCost'}

In [81]:
df_eu_org_14_20.info()

<class 'pandas.DataFrame'>
RangeIndex: 178920 entries, 0 to 178919
Data columns (total 25 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   projectID           178920 non-null  int64
 1   projectAcronym      178920 non-null  str
 2   organisationID      178920 non-null  int64
 3   vatNumber           160701 non-null  str
 4   name                178920 non-null  str
 5   shortName           138079 non-null  str
 6   SME                 178402 non-null  object
 7   activityType        178118 non-null  str
 8   street              177682 non-null  str
 9   postCode            176945 non-null  str
 10  city                178397 non-null  str
 11  country             178581 non-null  str
 12  nutsCode            178312 non-null  str
 13  geolocation         176715 non-null  str
 14  organizationURL     115790 non-null  str
 15  contactForm         178920 non-null  str
 16  contentUpdateDate   178920 non-null  str
 17  rcn                 178920 non-null  int64
 18  order               178906 non-null  float64
 19  role                178920 non-null  str
 20  ecContribution      171121 non-null  str
 21  netEcContribution   178913 non-null  str
 22  totalCost           178742 non-null  str
 23  endOfParticipation  178920 non-null  bool
 24  active              1386 non-null    object
dtypes: bool(1), float64(1), int64(3), object(2), str(18)
memory usage: 84.4+ MB

In [82]:
df_eu_proj_14_20.info()

<class 'pandas.DataFrame'>
RangeIndex: 35389 entries, 0 to 35388
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   projectID           35389 non-null  int64
 1   acronym             35389 non-null  str
 2   status              35389 non-null  str
 3   title               35389 non-null  str
 4   startDate           35389 non-null  str
 5   endDate             35389 non-null  str
 6   totalCost           35389 non-null  str
 7   ecMaxContribution   35389 non-null  str
 8   topics              35389 non-null  str
 9   ecSignatureDate     35389 non-null  str
 10  frameworkProgramme  35389 non-null  str
 11  masterCall          35389 non-null  str
 12  subCall             35389 non-null  str
 13  fundingScheme       35389 non-null  str
 14  objective           35389 non-null  str
 15  contentUpdateDate   35389 non-null  str
 16  rcn                 35389 non-null  str
 17  grantDoi            35389 non-null  str
 18  keywords            35337 non-null  str
 19  Human-validated     33713 non-null  str
 20  legalBasis          18158 non-null  str
 21  Unnamed: 21         373 non-null    str
dtypes: int64(1), str(21)
memory usage: 78.6 MB

In [83]:
df_eu_org_21_27.info()

<class 'pandas.DataFrame'>
RangeIndex: 136514 entries, 0 to 136513
Data columns (total 25 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   projectID           136514 non-null  int64
 1   projectAcronym      136514 non-null  str
 2   organisationID      136514 non-null  int64
 3   vatNumber           121395 non-null  str
 4   name                136514 non-null  str
 5   shortName           102032 non-null  str
 6   SME                 136169 non-null  object
 7   activityType        136512 non-null  str
 8   street              136106 non-null  str
 9   postCode            135492 non-null  str
 10  city                136169 non-null  str
 11  country             136496 non-null  str
 12  nutsCode            136149 non-null  str
 13  geolocation         134300 non-null  str
 14  organizationURL     83096 non-null   str
 15  contactForm         136514 non-null  str
 16  contentUpdateDate   136514 non-null  str
 17  rcn                 136514 non-null  int64
 18  order               136514 non-null  int64
 19  role                136514 non-null  str
 20  ecContribution      114019 non-null  str
 21  netEcContribution   136503 non-null  str
 22  totalCost           136470 non-null  str
 23  endOfParticipation  136514 non-null  bool
 24  active              0 non-null       float64
dtypes: bool(1), float64(1), int64(4), object(1), str(18)
memory usage: 64.4+ MB

In [84]:
df_eu_proj_21_27.info()

<class 'pandas.DataFrame'>
RangeIndex: 22528 entries, 0 to 22527
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   projectID           22528 non-null  int64
 1   acronym             22528 non-null  str
 2   status              22528 non-null  str
 3   title               22528 non-null  str
 4   startDate           22528 non-null  str
 5   endDate             22528 non-null  str
 6   totalCost           22528 non-null  str
 7   ecMaxContribution   22528 non-null  str
 8   topics              22528 non-null  str
 9   ecSignatureDate     22528 non-null  str
 10  frameworkProgramme  22528 non-null  str
 11  masterCall          22528 non-null  str
 12  subCall             22528 non-null  str
 13  fundingScheme       22528 non-null  str
 14  objective           22528 non-null  str
 15  contentUpdateDate   22528 non-null  str
 16  rcn                 22528 non-null  str
 17  grantDoi            22528 non-null  str
 18  keywords            22472 non-null  str
 19  Human-validated     21747 non-null  str
 20  legalBasis          20341 non-null  str
dtypes: int64(1), str(20)
memory usage: 51.5 MB

In [85]:
numeric_cols=["totalCost","totalContribution","ecMaxContribution","ecContribution","ecContributionEUR"]
date_cols=["startDate","endDate"]

for df in [df_eu_org_14_20, df_eu_proj_14_20, df_eu_org_21_27, df_eu_proj_21_27]:
    for col in numeric_cols:
        if col in df.columns:
            df[col]= (
                df[col]
                .astype(str)
                .str.replace(",",".",regex=False)
                .replace(["nan","None", ""],pd.NA)
            )
            df[col]=pd.to_numeric(df[col],errors="coerce")


for df in [df_eu_org_14_20, df_eu_proj_14_20, df_eu_org_21_27, df_eu_proj_21_27]:
    for col in date_cols:
        if col in df.columns:
            df[col]=pd.to_datetime(df[col],errors="coerce")

In [86]:
df_eu_org_14_20["totalCost"].info()

<class 'pandas.Series'>
RangeIndex: 178920 entries, 0 to 178919
Series name: totalCost
Non-Null Count   Dtype
--------------   -----
178742 non-null  float64
dtypes: float64(1)
memory usage: 1.4 MB

In [87]:
## Check if both columns have the same values 2014-2020 dataset
org_tot_cost_14_20= df_eu_org_14_20['totalCost'].sum()
proj_tot_cost_14_20= df_eu_proj_14_20['totalCost'].sum()

print(org_tot_cost_14_20)
print(proj_tot_cost_14_20)

84397236096.60825
83195590715.73401

In [88]:
## Check if both columns have the same values 2021-2027
org_tot_cost_21_27= df_eu_org_21_27['totalCost'].sum()
proj_tot_cost_21_27= df_eu_proj_21_27['totalCost'].sum()

print(org_tot_cost_21_27)
print(proj_tot_cost_21_27)

61567221464.89
61158888018.229996

After checking the information, the `Project` dataset is the one that contains the unique information related to each project, while the `Organizations` dataset brings the information related to all the laboratories and entities that are part of the projects.

Because the idea of this project is to understand the opportunity of potential customers, we will work with both datasets with major focus in Organizations.

We also realized that the cost information is not completely exact in both files. For example, in the `Project` file the total cost could be EUR 5,000, while in the `Organizations` file the cost could appear as EUR 5,010. Also the Total Cost column in the project table is related to the total cost of the project, while the organization total cost is the cost that was assign to the organization.

For this analysis, we will focus on the `totalCost` from the `Organizations` table.


Following steps:

1. Take the `Project` table and filter all the projects related to the MedTech field of the company.
2. Based on this filtered `Project` table, filter the projects in the `Organizations` table to check only the relevant entities for the company.

### Target Projects - Focus on Health & Medtech

In [122]:
keywords= [
    "laboratory automation", "lab automation",
    "liquid handling", "sample preparation", "workflow automation",    

    # Genomics / molecular biology
    "genomics", "genomic", "proteomics", "proteomic",
    "multi-omics", "multiomics", "transcriptomics", "metabolomics",
    "single cell", "sequencing", "next generation sequencing", "ngs",
    "pcr", "qpcr", "digital pcr", "rna", "dna",

    # Biomarkers / diagnostics
    "biomarker", "biomarkers",
    "diagnostics",  "molecular diagnostics",
    "clinical diagnostics", "ivd", "in vitro diagnostics",
    "liquid biopsy", "companion diagnostics",
    "genetic testing", "molecular profiling",
    "pathology", "molecular pathology",

    # Oncology / high-value clinical areas
    "oncology", "cancer", "tumor", "tumour",
    "leukemia", "leukaemia", "lymphoma", "carcinoma",
    "solid tumor", "solid tumour",

    # Cell / tissue / advanced therapies
    "cell therapy", "cart", "car-t", "t cell", "t-cell",
    "stem cell", "cell biology", "cellomics",
    "organoids", "3d cell", "cell and tissue",

    # Pharma / biotech
    "drug discovery", "drug development", "biopharma",
    "biotechnology", "personalized medicine", "precision medicine",

    # Digital / AI
    "bioinformatics", "data-driven", "digital health",

    # MedTech / OEM
    "medtech", "medical device", 
    "microfluidics"
]

In [90]:
def filter_projects_by_keywords(df, text_col="objective"):
    pattern = "|".join(re.escape(k.lower()) for k in keywords)
    return df[
        df[text_col]
        .fillna("")
        .str.lower()
        .str.contains(pattern, regex=True)
    ].copy()

In [91]:
df_eu_proj_14_20_final= filter_projects_by_keywords(df_eu_proj_14_20, text_col="objective")
df_eu_proj_21_27_final= filter_projects_by_keywords(df_eu_proj_21_27, text_col="objective")

In [92]:
df_eu_proj_14_20.info()

<class 'pandas.DataFrame'>
RangeIndex: 35389 entries, 0 to 35388
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   projectID           35389 non-null  int64
 1   acronym             35389 non-null  str
 2   status              35389 non-null  str
 3   title               35389 non-null  str
 4   startDate           35378 non-null  datetime64[us]
 5   endDate             35378 non-null  datetime64[us]
 6   totalCost           35378 non-null  float64
 7   ecMaxContribution   35378 non-null  float64
 8   topics              35389 non-null  str
 9   ecSignatureDate     35389 non-null  str
 10  frameworkProgramme  35389 non-null  str
 11  masterCall          35389 non-null  str
 12  subCall             35389 non-null  str
 13  fundingScheme       35389 non-null  str
 14  objective           35389 non-null  str
 15  contentUpdateDate   35389 non-null  str
 16  rcn                 35389 non-null  str
 17  grantDoi            35389 non-null  str
 18  keywords            35337 non-null  str
 19  Human-validated     33713 non-null  str
 20  legalBasis          18158 non-null  str
 21  Unnamed: 21         373 non-null    str
dtypes: datetime64[us](2), float64(2), int64(1), str(17)
memory usage: 77.4 MB

In [93]:
df_eu_proj_14_20_final.info()

<class 'pandas.DataFrame'>
Index: 19610 entries, 3 to 35384
Data columns (total 22 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   projectID           19610 non-null  int64
 1   acronym             19610 non-null  str
 2   status              19610 non-null  str
 3   title               19610 non-null  str
 4   startDate           19610 non-null  datetime64[us]
 5   endDate             19610 non-null  datetime64[us]
 6   totalCost           19610 non-null  float64
 7   ecMaxContribution   19610 non-null  float64
 8   topics              19610 non-null  str
 9   ecSignatureDate     19610 non-null  str
 10  frameworkProgramme  19610 non-null  str
 11  masterCall          19610 non-null  str
 12  subCall             19610 non-null  str
 13  fundingScheme       19610 non-null  str
 14  objective           19610 non-null  str
 15  contentUpdateDate   19610 non-null  str
 16  rcn                 19610 non-null  str
 17  grantDoi            19610 non-null  str
 18  keywords            19583 non-null  str
 19  Human-validated     18582 non-null  str
 20  legalBasis          9974 non-null   str
 21  Unnamed: 21         0 non-null      str
dtypes: datetime64[us](2), float64(2), int64(1), str(17)
memory usage: 43.7 MB

 Based on this filter we will filter the unique project for the `Organization` table and to analyze the opportunity there.

In [94]:
def build_opportunity_base (df_org, df_proj_filtered, proj_columns):
    """
    Build the opportunity base:
    1) Keep inly organizations linked to filtered project based on keywords.
    2) Add selected project-level columns
    """
    
    assert df_proj_filtered["projectID"].is_unique,"ProjectID is not unique in project table"
    
    df_org_filtered = df_org[df_org["projectID"].isin(df_proj_filtered["projectID"])].copy()
    
    df_final=df_org_filtered.merge(
        df_proj_filtered[proj_columns],
        how="left",
        on="projectID",
        validate="many_to_one"
    )
    
    return df_final

In [95]:
proj_columns = ['projectID','status', 'title', 'startDate','endDate','totalCost','topics','fundingScheme','grantDoi','keywords','objective']

In [96]:
df_eu_org_14_20_final=build_opportunity_base(
    df_org=df_eu_org_14_20,
    df_proj_filtered=df_eu_proj_14_20_final,
    proj_columns=proj_columns
)

In [97]:
df_eu_org_14_20_final.rename(columns={'totalCost_x':'totalCostOrg','totalCost_y':'totalCostProj'},inplace=True)
df_eu_org_14_20_final.columns

Index(['projectID', 'projectAcronym', 'organisationID', 'vatNumber', 'name',
       'shortName', 'SME', 'activityType', 'street', 'postCode', 'city',
       'country', 'nutsCode', 'geolocation', 'organizationURL', 'contactForm',
       'contentUpdateDate', 'rcn', 'order', 'role', 'ecContribution',
       'netEcContribution', 'totalCostOrg', 'endOfParticipation', 'active',
       'status', 'title', 'startDate', 'endDate', 'totalCostProj', 'topics',
       'fundingScheme', 'grantDoi', 'keywords', 'objective'],
      dtype='str')

In [98]:
df_eu_org_21_27_final=build_opportunity_base(
    df_org=df_eu_org_21_27,
    df_proj_filtered= df_eu_proj_21_27_final,
    proj_columns=proj_columns
)

In [99]:
df_eu_org_21_27_final.rename(columns={'totalCost_x':'totalCostOrg','totalCost_y':'totalCostProj'},inplace=True)
df_eu_org_21_27_final.columns

Index(['projectID', 'projectAcronym', 'organisationID', 'vatNumber', 'name',
       'shortName', 'SME', 'activityType', 'street', 'postCode', 'city',
       'country', 'nutsCode', 'geolocation', 'organizationURL', 'contactForm',
       'contentUpdateDate', 'rcn', 'order', 'role', 'ecContribution',
       'netEcContribution', 'totalCostOrg', 'endOfParticipation', 'active',
       'status', 'title', 'startDate', 'endDate', 'totalCostProj', 'topics',
       'fundingScheme', 'grantDoi', 'keywords', 'objective'],
      dtype='str')

Now we will consolidate both tables, and adding the `period` variable for each:

In [100]:
df_eu_org_14_20_final["period"] = "2014-2020"
df_eu_org_21_27_final["period"] = "2021-2027"

In [101]:
df_eu_cordis_db = pd.concat([df_eu_org_14_20_final,df_eu_org_21_27_final],ignore_index=True)

In [102]:
df_eu_cordis_db.columns

Index(['projectID', 'projectAcronym', 'organisationID', 'vatNumber', 'name',
       'shortName', 'SME', 'activityType', 'street', 'postCode', 'city',
       'country', 'nutsCode', 'geolocation', 'organizationURL', 'contactForm',
       'contentUpdateDate', 'rcn', 'order', 'role', 'ecContribution',
       'netEcContribution', 'totalCostOrg', 'endOfParticipation', 'active',
       'status', 'title', 'startDate', 'endDate', 'totalCostProj', 'topics',
       'fundingScheme', 'grantDoi', 'keywords', 'objective', 'period'],
      dtype='str')

In [107]:
df_eu_final_cols =['projectID','organisationID','name','shortName','activityType','city','country','role','ecContribution',
       'netEcContribution', 'totalCostOrg', 'endOfParticipation', 'active',
       'status', 'title', 'startDate', 'endDate', 'totalCostProj', 'topics',
       'fundingScheme', 'grantDoi', 'keywords', 'period','objective']

In [108]:
df_eu_cordis_db = df_eu_cordis_db[df_eu_final_cols].copy()

In [109]:
df_eu_cordis_db.shape

(177879, 24)

In [110]:
df_eu_cordis_db["period"].value_counts()

period
2014-2020    96967
2021-2027    80912
Name: count, dtype: int64

And we have the first data set :)

In [111]:
df_eu_cordis_db.to_csv("../../_local_data_backup/CordisDatabase.csv")

## 2. CLINICAL TRIAL DATASETS

Information download from: https://euclinicaltrials.eu/search-for-clinical-trials/?lang=en

In [146]:
os.getcwd()

'/Users/fernandacladeramelgar/Documents/2_Projects/TECAN_Application/SalesAnalytics/Scripts'

In [147]:
df_trials = pd.read_csv("data/data_raw/CTIS_trials_20260626.csv")
df_trials.head()

,Trial number,Protocol code,Title of the trial,Overall trial status,Location(s) and recruitment status,Age group,Age range secondary identifier,Gender,Number of participants enrolled,Trial region,...,Primary endpoint,Secondary endpoints,Decision date,Start date,End date,Global end of the trial,Trial results,Sponsor/Co-Sponsors,Sponsor type,Last updated
0,2023-509723-41-00,REALL_ CART,A Phase I Clinical Trial of CART cell therapy ...,Not authorised,Spain:Not authorised,"18-64 years, 0-17 years",NaN,"Female, Male",10,EEA only,...,"In this umbrella trial, we will determine in p...",Expression of CD19/CD22 and NKG2DL on primary ...,07/05/2024,NaN,NaN,NaN,No,Fundacion Para La Investigacion Biomedica Del ...,Patient organisation/association,07/05/2024
1,2023-510220-72-00,BRONCHIPHARMA I,PHARMACOLOGICAL STRATEGIES OF INHALED ANTIBIOT...,"Authorised, recruitment pending","Spain:Authorised, recruitment pending","65+ years, 18-64 years","65-84 years, 85+ years","Female, Male",75,EEA only,...,Number of colony forming units (CFU),NaN,03/06/2024,NaN,NaN,NaN,No,Consorci Mar Parc De Salut De Barcelona,Hospital/Clinic/Other health care facility,03/06/2024
2,2022-501417-31-00,MK-7684A-010,"A Phase 3, Randomized, Double-blind, Active-Co...",Not authorised,"Poland:Not authorised, Italy:Not authorised, G...","18-64 years, 65+ years, 0-17 years","12-17 years, 65-84 years, 85+ years, N/A","Female, Male",510,In both EEA and non-EEA,...,Recurrence-Free Survival (RFS),"Distant Metastasis-Free Survival (DMFS), Overa...",02/03/2023,NaN,NaN,NaN,No,Merck Sharp & Dohme LLC,Pharmaceutical company,06/03/2023
3,2024-512642-42-00,NaN,Randomized study to protect from radiation iat...,"Ongoing, recruiting","Italy:Ongoing, recruiting","65+ years, 0-17 years, 18-64 years",NaN,"Female, Male",65,EEA only,...,Hypothyroidism-free survival at 3 years after ...,NaN,24/05/2024,13/12/2021,NaN,NaN,No,Fondazione IRCCS Istituto Nazionale Dei Tumori,Hospital/Clinic/Other health care facility,24/05/2024
4,2023-504664-42-02,IP-VITD,REQUIRED DOSE OF CHOLECALCIFEROL IN THE MANAGE...,"Ongoing, recruiting","Spain:Ongoing, recruiting","65+ years, 18-64 years",NaN,Female,80,EEA only,...,"To evaluate the efficacy of cholecalciferol, s...",Vitamin D levels will be evaluated in the four...,27/06/2023,03/07/2023,NaN,NaN,No,Clinica Palacios Madrid S.L.,Hospital/Clinic/Other health care facility,27/06/2023

In [148]:
df_trials.columns

Index(['Trial number', 'Protocol code', 'Title of the trial',
       'Overall trial status', 'Location(s) and recruitment status',
       'Age group', 'Age range secondary identifier', 'Gender',
       'Number of participants enrolled', 'Trial region', 'Medical conditions',
       'Therapeutic area', 'Trial phase', 'Product', 'Primary endpoint',
       'Secondary endpoints', 'Decision date', 'Start date', 'End date',
       'Global end of the trial', 'Trial results', 'Sponsor/Co-Sponsors',
       'Sponsor type', 'Last updated'],
      dtype='str')

In [149]:
df_trials.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Trial number                        10000 non-null  str
 1   Protocol code                       8463 non-null   str
 2   Title of the trial                  10000 non-null  str
 3   Overall trial status                10000 non-null  str
 4   Location(s) and recruitment status  10000 non-null  str
 5   Age group                           10000 non-null  str
 6   Age range secondary identifier      3623 non-null   str
 7   Gender                              10000 non-null  str
 8   Number of participants enrolled     10000 non-null  int64
 9   Trial region                        9999 non-null   str
 10  Medical conditions                  9997 non-null   str
 11  Therapeutic area                    10000 non-null  str
 12  Trial phase                         10000 non-null  str
 13  Product                             7965 non-null   str
 14  Primary endpoint                    8140 non-null   str
 15  Secondary endpoints                 7309 non-null   str
 16  Decision date                       10000 non-null  str
 17  Start date                          8458 non-null   str
 18  End date                            2966 non-null   str
 19  Global end of the trial             1192 non-null   str
 20  Trial results                       10000 non-null  str
 21  Sponsor/Co-Sponsors                 10000 non-null  str
 22  Sponsor type                        10000 non-null  str
 23  Last updated                        10000 non-null  str
dtypes: int64(1), str(23)
memory usage: 17.0 MB

In [150]:
df_trials.columns = (
    df_trials.columns
    .str.strip()
    .str.replace(" ", "_", regex=False)
    .str.replace("/", "_", regex=False)
)
df_trials.columns

Index(['Trial_number', 'Protocol_code', 'Title_of_the_trial',
       'Overall_trial_status', 'Location(s)_and_recruitment_status',
       'Age_group', 'Age_range_secondary_identifier', 'Gender',
       'Number_of_participants_enrolled', 'Trial_region', 'Medical_conditions',
       'Therapeutic_area', 'Trial_phase', 'Product', 'Primary_endpoint',
       'Secondary_endpoints', 'Decision_date', 'Start_date', 'End_date',
       'Global_end_of_the_trial', 'Trial_results', 'Sponsor_Co-Sponsors',
       'Sponsor_type', 'Last_updated'],
      dtype='str')

In [151]:
date_cols_trials = [
    "Decision_date",
    "Start_date",
    "End_date",
    "Global_end_of_the_trial",
    "Last_updated"
]

for col in date_cols_trials:
    df_trials[col]=pd.to_datetime(df_trials[col],errors="coerce")

/var/folders/_z/vq1q1pzj639b28jbhlxzd0zw0000gn/T/ipykernel_21635/2708697362.py:10: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_trials[col]=pd.to_datetime(df_trials[col],errors="coerce")
/var/folders/_z/vq1q1pzj639b28jbhlxzd0zw0000gn/T/ipykernel_21635/2708697362.py:10: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_trials[col]=pd.to_datetime(df_trials[col],errors="coerce")
/var/folders/_z/vq1q1pzj639b28jbhlxzd0zw0000gn/T/ipykernel_21635/2708697362.py:10: UserWarning: Parsing dates in %d/%m/%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_trials[col]=pd.to_datetime(df_trials[col],errors="coerce")

In [152]:
df_trials.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 24 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Trial_number                        10000 non-null  str
 1   Protocol_code                       8463 non-null   str
 2   Title_of_the_trial                  10000 non-null  str
 3   Overall_trial_status                10000 non-null  str
 4   Location(s)_and_recruitment_status  10000 non-null  str
 5   Age_group                           10000 non-null  str
 6   Age_range_secondary_identifier      3623 non-null   str
 7   Gender                              10000 non-null  str
 8   Number_of_participants_enrolled     10000 non-null  int64
 9   Trial_region                        9999 non-null   str
 10  Medical_conditions                  9997 non-null   str
 11  Therapeutic_area                    10000 non-null  str
 12  Trial_phase                         10000 non-null  str
 13  Product                             7965 non-null   str
 14  Primary_endpoint                    8140 non-null   str
 15  Secondary_endpoints                 7309 non-null   str
 16  Decision_date                       3835 non-null   datetime64[us]
 17  Start_date                          8458 non-null   datetime64[us]
 18  End_date                            2966 non-null   datetime64[us]
 19  Global_end_of_the_trial             1192 non-null   datetime64[us]
 20  Trial_results                       10000 non-null  str
 21  Sponsor_Co-Sponsors                 10000 non-null  str
 22  Sponsor_type                        10000 non-null  str
 23  Last_updated                        3818 non-null   datetime64[us]
dtypes: datetime64[us](5), int64(1), str(18)
memory usage: 16.7 MB

In [153]:
trial_text_cols = [
    "Title_of_the_trial",
    "Overall_trial_status",
    "Location(s)_and_recruitment_status",
    "Trial_region",
    "Medical_conditions",
    "Therapeutic_area",
    "Trial_phase",
    "Product",
    "Primary_endpoint",
    "Secondary_endpoints",
    "Trial_results",
    "Sponsor_Co-Sponsors",
    "Sponsor_type"
]

In [154]:
def filter_trials_by_keywords(df, keywords, text_cols):
    pattern = "|".join(re.escape(k.lower()) for k in keywords)

    combined_text = (
        df[text_cols]
        .fillna("")
        .astype(str)
        .agg(" ".join, axis=1)
        .str.lower()
    )

    mask = combined_text.str.contains(pattern, regex=True, na=False)

    return df.loc[mask, text_cols].copy()

In [155]:
df_trials_final = filter_trials_by_keywords(
    df=df_trials,
    keywords=keywords,
    text_cols=trial_text_cols
)

In [156]:
df_trials.shape

(10000, 24)

In [157]:
df_trials_final.shape

(5230, 13)

In [158]:
df_trials_final.to_csv("../Scripts/data/data_final/TrialsDatabase.csv")