# **MACRO ANALYSIS AND OPPORTUNITIES FOR LIFESCIENCE INDUSTRY EUROPE**

The following work was made to analyze the opportunities in the European Market for companies in the Medtech.

**Source of Information**:

1) Company Reports: We get the financial reports of the company for the last three years.
2) CORDIS - EU research projects under HORIZON EUROPE (2021 - 2027)
3) Clinical Trias Information from *"https://clinicaltrials.gov/api/v2/studies"*
4) US information used for comparison purpose: *"https://api.reporter.nih.gov/v2/projects/search"*

## 1. CORDIS - EU RESEARCH PROJECTS UNDER HORIZON EUROPE

### Libraries

In [56]:
import sys
!{sys.executable} -m pip install openpyxl
import zipfile
import requests
import urllib.request
import pandas as pd
from pathlib import Path
import os
import re
os.getcwd()

Requirement already satisfied: openpyxl in /opt/anaconda3/envs/env/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/anaconda3/envs/env/lib/python3.12/site-packages (from openpyxl) (2.0.0)

'/Users/fernandacladeramelgar/Documents/2_Projects/TECAN_Application/SalesAnalytics/Scripts'

### 2014 - 2020 Dataset

In [3]:
url_2014_2020="https://cordis.europa.eu/data/cordis-h2020projects-xlsx.zip"
reports_dir= Path("data/Reports")
reports_dir.mkdir(parents=True, exist_ok=True)
zip_path = reports_dir / "cordis-h2020projects-xlsx.zip"
urllib.request.urlretrieve(url_2014_2020, zip_path)
with zipfile.ZipFile(zip_path, 'r') as z:
    z.extract("project.xlsx",reports_dir)
    z.extract("organization.xlsx",reports_dir)
    
(reports_dir / "project.xlsx").rename(reports_dir/"project_2014_2020.xlsx")
(reports_dir / "organization.xlsx").rename(reports_dir/"organization_2014_2020.xlsx")

PosixPath('data/Reports/organization_2014_2020.xlsx')

In [5]:
df_eu_org_14_20=pd.read_excel(reports_dir/"organization_2021_2027.xlsx", engine='openpyxl')
df_eu_proj_14_20=pd.read_excel(reports_dir/"project_2021_2027.xlsx", engine='openpyxl')

/opt/anaconda3/envs/env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/anaconda3/envs/env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

### 2021 - 2027 Dataset

In [4]:
url_2021_2027="https://cordis.europa.eu/data/cordis-HORIZONprojects-xlsx.zip"
reports_dir= Path("data/Reports")
reports_dir.mkdir(parents=True, exist_ok=True)
zip_path = reports_dir / "cordis-HORIZONprojects-xlsx.zip"
urllib.request.urlretrieve(url_2021_2027, zip_path)
with zipfile.ZipFile(zip_path, 'r') as z:
    z.extract("project.xlsx",reports_dir)
    z.extract("organization.xlsx",reports_dir)
    
(reports_dir / "project.xlsx").rename(reports_dir/"project_2021_2027.xlsx")
(reports_dir / "organization.xlsx").rename(reports_dir/"organization_2021_2027.xlsx")

PosixPath('data/Reports/organization_2021_2027.xlsx')

In [6]:
df_eu_org_21_27=pd.read_excel(reports_dir/"organization_2021_2027.xlsx", engine='openpyxl')
df_eu_proj_21_27=pd.read_excel(reports_dir/"project_2021_2027.xlsx", engine='openpyxl')

/opt/anaconda3/envs/env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")
/opt/anaconda3/envs/env/lib/python3.12/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

### Understanding the Data Structure

In [7]:
df_eu_org_14_20.head()

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,101069359,SolDAC,912743326,ESB98896137,LOMARTOV SL,LOMARTOV APPLIED INNOVATION ENGINEERING,True,PRC,CALLE ALFARERIA 3,46100,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,3146679,2,participant,299250,299250,299250,False,NaN
1,101069359,SolDAC,898206033,BE0746474089,EUROPEAN INNOVATION MARKETPLACE ASBL,NaN,False,REC,TRIERSTRAAT 49 STRATENPLAN BUS 7,1040,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1965819,6,participant,149125,149125,149125,False,NaN
2,101069359,SolDAC,928228018,ESB66340514,"COMET GLOBAL INNOVATION, SL",COMET,True,PRC,"C GRAN DE GRACIA NUM 1, PLANTA 4, PUERTA 3",08012,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1947059,1,coordinator,451500,451500,451500,False,NaN
3,101069359,SolDAC,999984253,GB607606448,THE UNIVERSITY COURT OF THE UNIVERSITY OF ST A...,USTAN,False,HES,NORTH STREET 66 COLLEGE GATE,KY16 9AJ,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1906637,8,associatedPartner,NaN,0,0,False,NaN
4,101069359,SolDAC,996435993,ESG64946387,FUNDACIO INSTITUT DE RECERCA EN ENERGIA DE CAT...,IREC-CERCA,False,REC,C/ JARDINS DE LES DONES DE NEGRE 1,08930,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1913642,3,participant,"399593,75","399593,75","399593,75",False,NaN

In [22]:
df_eu_org_21_27.head()

,projectID,projectAcronym,organisationID,vatNumber,name,shortName,SME,activityType,street,postCode,...,contactForm,contentUpdateDate,rcn,order,role,ecContribution,netEcContribution,totalCost,endOfParticipation,active
0,101069359,SolDAC,912743326,ESB98896137,LOMARTOV SL,LOMARTOV APPLIED INNOVATION ENGINEERING,True,PRC,CALLE ALFARERIA 3,46100,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,3146679,2,participant,299250,299250,299250,False,NaN
1,101069359,SolDAC,898206033,BE0746474089,EUROPEAN INNOVATION MARKETPLACE ASBL,NaN,False,REC,TRIERSTRAAT 49 STRATENPLAN BUS 7,1040,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1965819,6,participant,149125,149125,149125,False,NaN
2,101069359,SolDAC,928228018,ESB66340514,"COMET GLOBAL INNOVATION, SL",COMET,True,PRC,"C GRAN DE GRACIA NUM 1, PLANTA 4, PUERTA 3",08012,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1947059,1,coordinator,451500,451500,451500,False,NaN
3,101069359,SolDAC,999984253,GB607606448,THE UNIVERSITY COURT OF THE UNIVERSITY OF ST A...,USTAN,False,HES,NORTH STREET 66 COLLEGE GATE,KY16 9AJ,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1906637,8,associatedPartner,NaN,0,0,False,NaN
4,101069359,SolDAC,996435993,ESG64946387,FUNDACIO INSTITUT DE RECERCA EN ENERGIA DE CAT...,IREC-CERCA,False,REC,C/ JARDINS DE LES DONES DE NEGRE 1,08930,...,https://ec.europa.eu/info/funding-tenders/oppo...,2026-03-27 15:10:23,1913642,3,participant,"399593,75","399593,75","399593,75",False,NaN

In [8]:
df_eu_proj_14_20.head()

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,topics,ecSignatureDate,...,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords,Human-validated,legalBasis
0,101069359,SolDAC,SIGNED,Full spectrum SOLar Direct Air Capture & conve...,2022-09-01,2025-08-31,"2073781,25","2073781,25",HORIZON-CL5-2021-D2-01-11,2022-05-12,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-RIA,Ethylene is the chemical industry’s primary bu...,2026-03-27 15:10:23,237915,10.3030/101069359,"zero-carbon, solar energy, air mining, Negativ...",true,HORIZON.2.5
1,101069357,Photo2Fuel,SIGNED,Artificial PHOTOsynthesis to produce FUELs and...,2022-09-01,2025-08-31,"2493171,25",2493171,HORIZON-CL5-2021-D2-01-08,2022-05-18,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-RIA,The Photo2Fuel project will develop a breakthr...,2026-02-12 19:21:26,237916,10.3030/101069357,solar energy; bacteria; archaea; solar fuels; ...,true,HORIZON.2.5
2,101069586,BOLSTER,SIGNED,Bridging Organizations and marginalized commun...,2022-09-01,2025-08-31,3792955,3792955,HORIZON-CL5-2021-D2-01-12,2022-06-10,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-RIA,No European should be put at a disadvantaged b...,2025-09-30 15:22:06,237917,10.3030/101069586,"Transition strategies, Participation, Margin...",true,HORIZON.2.5
3,101069604,GREENET,SIGNED,NCPS NETwork for the GREEN transition in clima...,2022-07-01,2027-12-31,"3250901,25","3250901,25",HORIZON-CL5-2021-D2-01-15,2022-06-09,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-CSA,The overall aim of GREENET is to improve the p...,2026-05-03 20:09:37,237918,10.3030/101069604,"Competence development, Capacity building, CL5...",NaN,HORIZON.2.5
4,101069529,SSH CENTRE,SIGNED,"Social Sciences and Humanities for Climate, En...",2022-09-01,2026-02-28,"2305696,25",2305696,HORIZON-CL5-2021-D2-01-13,2022-05-20,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-CSA,"The Social Sciences & Humanities for Climate, ...",2026-04-15 15:27:43,237919,10.3030/101069529,Transitions; Transdisciplinary; Epistemic cult...,true,HORIZON.2.5

In [23]:
df_eu_proj_21_27.head()

,id,acronym,status,title,startDate,endDate,totalCost,ecMaxContribution,topics,ecSignatureDate,...,masterCall,subCall,fundingScheme,objective,contentUpdateDate,rcn,grantDoi,keywords,Human-validated,legalBasis
0,101069359,SolDAC,SIGNED,Full spectrum SOLar Direct Air Capture & conve...,2022-09-01,2025-08-31,"2073781,25","2073781,25",HORIZON-CL5-2021-D2-01-11,2022-05-12,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-RIA,Ethylene is the chemical industry’s primary bu...,2026-03-27 15:10:23,237915,10.3030/101069359,"zero-carbon, solar energy, air mining, Negativ...",true,HORIZON.2.5
1,101069357,Photo2Fuel,SIGNED,Artificial PHOTOsynthesis to produce FUELs and...,2022-09-01,2025-08-31,"2493171,25",2493171,HORIZON-CL5-2021-D2-01-08,2022-05-18,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-RIA,The Photo2Fuel project will develop a breakthr...,2026-02-12 19:21:26,237916,10.3030/101069357,solar energy; bacteria; archaea; solar fuels; ...,true,HORIZON.2.5
2,101069586,BOLSTER,SIGNED,Bridging Organizations and marginalized commun...,2022-09-01,2025-08-31,3792955,3792955,HORIZON-CL5-2021-D2-01-12,2022-06-10,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-RIA,No European should be put at a disadvantaged b...,2025-09-30 15:22:06,237917,10.3030/101069586,"Transition strategies, Participation, Margin...",true,HORIZON.2.5
3,101069604,GREENET,SIGNED,NCPS NETwork for the GREEN transition in clima...,2022-07-01,2027-12-31,"3250901,25","3250901,25",HORIZON-CL5-2021-D2-01-15,2022-06-09,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-CSA,The overall aim of GREENET is to improve the p...,2026-05-03 20:09:37,237918,10.3030/101069604,"Competence development, Capacity building, CL5...",NaN,HORIZON.2.5
4,101069529,SSH CENTRE,SIGNED,"Social Sciences and Humanities for Climate, En...",2022-09-01,2026-02-28,"2305696,25",2305696,HORIZON-CL5-2021-D2-01-13,2022-05-20,...,HORIZON-CL5-2021-D2-01,HORIZON-CL5-2021-D2-01,HORIZON-CSA,"The Social Sciences & Humanities for Climate, ...",2026-04-15 15:27:43,237919,10.3030/101069529,Transitions; Transdisciplinary; Epistemic cult...,true,HORIZON.2.5

In [11]:
df_eu_org_14_20.columns

Index(['projectID', 'projectAcronym', 'organisationID', 'vatNumber', 'name',
       'shortName', 'SME', 'activityType', 'street', 'postCode', 'city',
       'country', 'nutsCode', 'geolocation', 'organizationURL', 'contactForm',
       'contentUpdateDate', 'rcn', 'order', 'role', 'ecContribution',
       'netEcContribution', 'totalCost', 'endOfParticipation', 'active'],
      dtype='object')

In [25]:
df_eu_org_21_27.columns

Index(['projectID', 'projectAcronym', 'organisationID', 'vatNumber', 'name',
       'shortName', 'SME', 'activityType', 'street', 'postCode', 'city',
       'country', 'nutsCode', 'geolocation', 'organizationURL', 'contactForm',
       'contentUpdateDate', 'rcn', 'order', 'role', 'ecContribution',
       'netEcContribution', 'totalCost', 'endOfParticipation', 'active'],
      dtype='object')

In [26]:
common_eu_org_cols=set(df_eu_org_14_20.columns).intersection(set(df_eu_org_21_27.columns))
common_eu_org_cols

{'SME',
 'active',
 'activityType',
 'city',
 'contactForm',
 'contentUpdateDate',
 'country',
 'ecContribution',
 'endOfParticipation',
 'geolocation',
 'name',
 'netEcContribution',
 'nutsCode',
 'order',
 'organisationID',
 'organizationURL',
 'postCode',
 'projectAcronym',
 'projectID',
 'rcn',
 'role',
 'shortName',
 'street',
 'totalCost',
 'vatNumber'}

In [12]:
df_eu_proj_14_20.columns

Index(['id', 'acronym', 'status', 'title', 'startDate', 'endDate', 'totalCost',
       'ecMaxContribution', 'topics', 'ecSignatureDate', 'frameworkProgramme',
       'masterCall', 'subCall', 'fundingScheme', 'objective',
       'contentUpdateDate', 'rcn', 'grantDoi', 'keywords', 'Human-validated',
       'legalBasis'],
      dtype='object')

In [27]:
df_eu_proj_21_27.columns

Index(['id', 'acronym', 'status', 'title', 'startDate', 'endDate', 'totalCost',
       'ecMaxContribution', 'topics', 'ecSignatureDate', 'frameworkProgramme',
       'masterCall', 'subCall', 'fundingScheme', 'objective',
       'contentUpdateDate', 'rcn', 'grantDoi', 'keywords', 'Human-validated',
       'legalBasis'],
      dtype='object')

In [29]:
common_eu_proj_cols=set(df_eu_proj_14_20.columns).intersection(set(df_eu_proj_21_27.columns))
common_eu_proj_cols

{'Human-validated',
 'acronym',
 'contentUpdateDate',
 'ecMaxContribution',
 'ecSignatureDate',
 'endDate',
 'frameworkProgramme',
 'fundingScheme',
 'grantDoi',
 'keywords',
 'legalBasis',
 'masterCall',
 'objective',
 'rcn',
 'startDate',
 'status',
 'subCall',
 'title',
 'topics',
 'totalCost'}

In [30]:
df_eu_proj_14_20.rename(columns={'id':'projectID'}, inplace=True)
df_eu_proj_14_20.columns

Index(['projectID', 'acronym', 'status', 'title', 'startDate', 'endDate',
       'totalCost', 'ecMaxContribution', 'topics', 'ecSignatureDate',
       'frameworkProgramme', 'masterCall', 'subCall', 'fundingScheme',
       'objective', 'contentUpdateDate', 'rcn', 'grantDoi', 'keywords',
       'Human-validated', 'legalBasis'],
      dtype='object')

In [31]:
df_eu_proj_21_27.rename(columns={'id':'projectID'}, inplace=True)
df_eu_proj_21_27.columns

Index(['projectID', 'acronym', 'status', 'title', 'startDate', 'endDate',
       'totalCost', 'ecMaxContribution', 'topics', 'ecSignatureDate',
       'frameworkProgramme', 'masterCall', 'subCall', 'fundingScheme',
       'objective', 'contentUpdateDate', 'rcn', 'grantDoi', 'keywords',
       'Human-validated', 'legalBasis'],
      dtype='object')

In [32]:
common_cols=set(df_eu_proj_14_20.columns).intersection(set(df_eu_org_14_20.columns))
common_cols

{'contentUpdateDate', 'projectID', 'rcn', 'totalCost'}

In [33]:
common_cols=set(df_eu_proj_21_27.columns).intersection(set(df_eu_org_21_27.columns))
common_cols

{'contentUpdateDate', 'projectID', 'rcn', 'totalCost'}

In [34]:
df_eu_org_14_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136514 entries, 0 to 136513
Data columns (total 25 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   projectID           136514 non-null  int64
 1   projectAcronym      136514 non-null  object
 2   organisationID      136514 non-null  int64
 3   vatNumber           121395 non-null  object
 4   name                136514 non-null  object
 5   shortName           102032 non-null  object
 6   SME                 136169 non-null  object
 7   activityType        136512 non-null  object
 8   street              136106 non-null  object
 9   postCode            135492 non-null  object
 10  city                136169 non-null  object
 11  country             136496 non-null  object
 12  nutsCode            136149 non-null  object
 13  geolocation         134300 non-null  object
 14  organizationURL     83096 non-null   object
 15  contactForm         136514 non-null  object
 16  contentUpdateDate   136514 non-null  object
 17  rcn                 136514 non-null  int64
 18  order               136514 non-null  int64
 19  role                136514 non-null  object
 20  ecContribution      114019 non-null  object
 21  netEcContribution   136503 non-null  object
 22  totalCost           136470 non-null  object
 23  endOfParticipation  136514 non-null  bool
 24  active              0 non-null       float64
dtypes: bool(1), float64(1), int64(4), object(19)
memory usage: 25.1+ MB

In [35]:
df_eu_proj_14_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22528 entries, 0 to 22527
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   projectID           22528 non-null  int64
 1   acronym             22528 non-null  object
 2   status              22528 non-null  object
 3   title               22528 non-null  object
 4   startDate           22528 non-null  object
 5   endDate             22528 non-null  object
 6   totalCost           22528 non-null  object
 7   ecMaxContribution   22528 non-null  object
 8   topics              22528 non-null  object
 9   ecSignatureDate     22528 non-null  object
 10  frameworkProgramme  22528 non-null  object
 11  masterCall          22528 non-null  object
 12  subCall             22528 non-null  object
 13  fundingScheme       22528 non-null  object
 14  objective           22528 non-null  object
 15  contentUpdateDate   22528 non-null  object
 16  rcn                 22528 non-null  object
 17  grantDoi            22528 non-null  object
 18  keywords            22472 non-null  object
 19  Human-validated     21747 non-null  object
 20  legalBasis          20341 non-null  object
dtypes: int64(1), object(20)
memory usage: 3.6+ MB

In [36]:
df_eu_org_21_27.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136514 entries, 0 to 136513
Data columns (total 25 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   projectID           136514 non-null  int64
 1   projectAcronym      136514 non-null  object
 2   organisationID      136514 non-null  int64
 3   vatNumber           121395 non-null  object
 4   name                136514 non-null  object
 5   shortName           102032 non-null  object
 6   SME                 136169 non-null  object
 7   activityType        136512 non-null  object
 8   street              136106 non-null  object
 9   postCode            135492 non-null  object
 10  city                136169 non-null  object
 11  country             136496 non-null  object
 12  nutsCode            136149 non-null  object
 13  geolocation         134300 non-null  object
 14  organizationURL     83096 non-null   object
 15  contactForm         136514 non-null  object
 16  contentUpdateDate   136514 non-null  object
 17  rcn                 136514 non-null  int64
 18  order               136514 non-null  int64
 19  role                136514 non-null  object
 20  ecContribution      114019 non-null  object
 21  netEcContribution   136503 non-null  object
 22  totalCost           136470 non-null  object
 23  endOfParticipation  136514 non-null  bool
 24  active              0 non-null       float64
dtypes: bool(1), float64(1), int64(4), object(19)
memory usage: 25.1+ MB

In [37]:
df_eu_proj_21_27.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22528 entries, 0 to 22527
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   projectID           22528 non-null  int64
 1   acronym             22528 non-null  object
 2   status              22528 non-null  object
 3   title               22528 non-null  object
 4   startDate           22528 non-null  object
 5   endDate             22528 non-null  object
 6   totalCost           22528 non-null  object
 7   ecMaxContribution   22528 non-null  object
 8   topics              22528 non-null  object
 9   ecSignatureDate     22528 non-null  object
 10  frameworkProgramme  22528 non-null  object
 11  masterCall          22528 non-null  object
 12  subCall             22528 non-null  object
 13  fundingScheme       22528 non-null  object
 14  objective           22528 non-null  object
 15  contentUpdateDate   22528 non-null  object
 16  rcn                 22528 non-null  object
 17  grantDoi            22528 non-null  object
 18  keywords            22472 non-null  object
 19  Human-validated     21747 non-null  object
 20  legalBasis          20341 non-null  object
dtypes: int64(1), object(20)
memory usage: 3.6+ MB

In [39]:
numeric_cols=["totalCost","totalContribution","ecMaxContribution","ecContribution","ecContributionEUR"]
date_cols=["startDate","endDate"]

for df in [df_eu_org_14_20, df_eu_proj_14_20, df_eu_org_21_27, df_eu_proj_21_27]:
    for col in numeric_cols:
        if col in df.columns:
            df[col]= (
                df[col]
                .astype(str)
                .str.replace(",","",regex=False)
                .replace(["nan","None", ""],pd.NA)
            )
            df[col]=pd.to_numeric(df[col],errors="coerce")


for df in [df_eu_org_14_20, df_eu_proj_14_20, df_eu_org_21_27, df_eu_proj_21_27]:
    for col in date_cols:
        if col in df.columns:
            df[col]=pd.to_datetime(df[col],errors="coerce")

In [45]:
df_eu_org_14_20["totalCost"].info()

<class 'pandas.core.series.Series'>
RangeIndex: 136514 entries, 0 to 136513
Series name: totalCost
Non-Null Count   Dtype
--------------   -----
136470 non-null  float64
dtypes: float64(1)
memory usage: 1.0 MB

In [ ]:
## Check if both columns have the same values 2014-2020 dataset
org_tot_cost_14_20= df_eu_org_14_20['totalCost'].sum()
proj_tot_cost_14_20= df_eu_proj_14_20['totalCost'].sum()

print(org_tot_cost_14_20)
print(proj_tot_cost_14_20)

1808219646637.0
2913879943076

In [47]:
## Check if both columns have the same values 2021-2027
org_tot_cost_21_27= df_eu_org_21_27['totalCost'].sum()
proj_tot_cost_21_27= df_eu_proj_21_27['totalCost'].sum()

print(org_tot_cost_21_27)
print(proj_tot_cost_21_27)

1808219646637.0
2913879943076

After checking the information, the `Project` dataset is the one that contains the unique information related to each project, while the `Organizations` dataset brings the information related to all the laboratories and entities that are part of the projects.

Because the idea of this project is to understand the opportunity of potential customers, we will work with both datasets with major focus in Organizations.

We also realized that the cost information is not completely exact in both files. For example, in the `Project` file the total cost could be EUR 5,000, while in the `Organizations` file the cost could appear as EUR 5,010. Also the Total Cost column in the project table is related to the total cost of the project, while the organization total cost is the cost that was assign to the organization.

For this analysis, we will focus on the `totalCost` from the `Organizations` table.


Following steps:

1. Take the `Project` table and filter all the projects related to the MedTech field of the company.
2. Based on this filtered `Project` table, filter the projects in the `Organizations` table to check only the relevant entities for the company.

### Target Projects - Focus on Health & Medtech

In [50]:
keywords = [
    # Core Tecan business
    "laboratory automation", "lab automation", "automation",
    "liquid handling", "sample preparation", "workflow automation",
    "robotics", "robotic", "high-throughput", "screening",

    # Life Sciences focus
    "genomics", "proteomics", "multi-omics", "multiomics",
    "cell biology", "cellomics", "single cell", "cell and tissue",
    "organoids", "3d cell", "assay", "biomarker",

    # Diagnostics / clinical
    "diagnostics", "molecular diagnostics", "clinical diagnostics",
    "ivd", "in vitro diagnostics", "liquid biopsy",
    "genetic testing", "companion diagnostics",

    # Pharma / biotech
    "drug discovery", "drug development", "biopharma",
    "biotechnology", "personalized medicine", "precision medicine",
    "adme", "tox", "quality control",

    # Digital / AI relevance
    "artificial intelligence", "machine learning",
    "bioinformatics", "data-driven", "digital health",

    # Partnering / OEM / MedTech
    "medtech", "medical device", "oem", "cdmo",
    "contract manufacturing", "microfluidics"
]

In [57]:
def filter_projects_by_keywords(df, text_col="objective"):
    pattern = "|".join(re.escape(k.lower()) for k in keywords)
    return df[
        df[text_col]
        .fillna("")
        .str.lower()
        .str.contains(pattern, regex=True)
    ].copy()

In [59]:
df_eu_proj_14_20_final= filter_projects_by_keywords(df_eu_proj_14_20, text_col="objective")

df_eu_proj_21_27_final= filter_projects_by_keywords(df_eu_proj_21_27, text_col="objective")

In [61]:
df_eu_proj_14_20.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22528 entries, 0 to 22527
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   projectID           22528 non-null  int64
 1   acronym             22528 non-null  object
 2   status              22528 non-null  object
 3   title               22528 non-null  object
 4   startDate           22528 non-null  datetime64[ns]
 5   endDate             22528 non-null  datetime64[ns]
 6   totalCost           22528 non-null  int64
 7   ecMaxContribution   22528 non-null  int64
 8   topics              22528 non-null  object
 9   ecSignatureDate     22528 non-null  object
 10  frameworkProgramme  22528 non-null  object
 11  masterCall          22528 non-null  object
 12  subCall             22528 non-null  object
 13  fundingScheme       22528 non-null  object
 14  objective           22528 non-null  object
 15  contentUpdateDate   22528 non-null  object
 16  rcn                 22528 non-null  object
 17  grantDoi            22528 non-null  object
 18  keywords            22472 non-null  object
 19  Human-validated     21747 non-null  object
 20  legalBasis          20341 non-null  object
dtypes: datetime64[ns](2), int64(3), object(16)
memory usage: 3.6+ MB

In [62]:
df_eu_proj_14_20_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6946 entries, 8 to 22522
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   projectID           6946 non-null   int64
 1   acronym             6946 non-null   object
 2   status              6946 non-null   object
 3   title               6946 non-null   object
 4   startDate           6946 non-null   datetime64[ns]
 5   endDate             6946 non-null   datetime64[ns]
 6   totalCost           6946 non-null   int64
 7   ecMaxContribution   6946 non-null   int64
 8   topics              6946 non-null   object
 9   ecSignatureDate     6946 non-null   object
 10  frameworkProgramme  6946 non-null   object
 11  masterCall          6946 non-null   object
 12  subCall             6946 non-null   object
 13  fundingScheme       6946 non-null   object
 14  objective           6946 non-null   object
 15  contentUpdateDate   6946 non-null   object
 16  rcn                 6946 non-null   object
 17  grantDoi            6946 non-null   object
 18  keywords            6941 non-null   object
 19  Human-validated     6845 non-null   object
 20  legalBasis          6178 non-null   object
dtypes: datetime64[ns](2), int64(3), object(16)
memory usage: 1.2+ MB

So we reduce from 22K rows of the projects to 6K project related to the company focus. 
Based on this filter we will filter the unique project for the `Organization` table and to analyze the opportunity there.

In [68]:
def build_opportunity_base (df_org, df_proj_filtered, proj_columns):
    """
    Build the opportunity base:
    1) Keep inly organizations linked to filtered project based on keywords.
    2) Add selected project-level columns
    """
    
    assert df_proj_filtered["projectID"].is_unique,"ProjectID is not unique in project table"
    
    df_org_filtered = df_org[df_org["projectID"].isin(df_proj_filtered["projectID"])].copy()
    
    df_final=df_org_filtered.merge(
        df_proj_filtered[proj_columns],
        how="left",
        on="projectID",
        validate="many_to_one"
    )
    
    return df_final

In [69]:
proj_columns = ['projectID','status', 'title', 'startDate','endDate','totalCost','topics','fundingScheme','grantDoi','keywords']

In [70]:
df_eu_org_14_20_final=build_opportunity_base(
    df_org=df_eu_org_14_20,
    df_proj_filtered=df_eu_proj_14_20_final,
    proj_columns=proj_columns
)

In [77]:
df_eu_org_14_20_final.rename(columns={'totalCost_x':'totalCostOrg','totalCost_y':'totalCostProj'},inplace=True)
df_eu_org_14_20_final.columns

Index(['projectID', 'projectAcronym', 'organisationID', 'vatNumber', 'name',
       'shortName', 'SME', 'activityType', 'street', 'postCode', 'city',
       'country', 'nutsCode', 'geolocation', 'organizationURL', 'contactForm',
       'contentUpdateDate', 'rcn', 'order', 'role', 'ecContribution',
       'netEcContribution', 'totalCostOrg', 'endOfParticipation', 'active',
       'status', 'title', 'startDate', 'endDate', 'totalCostProj', 'topics',
       'fundingScheme', 'grantDoi', 'keywords'],
      dtype='object')

In [80]:
df_eu_org_21_27_final=build_opportunity_base(
    df_org=df_eu_org_21_27,
    df_proj_filtered= df_eu_proj_21_27_final,
    proj_columns=proj_columns
)

In [81]:
df_eu_org_21_27_final.rename(columns={'totalCost_x':'totalCostOrg','totalCost_y':'totalCostProj'},inplace=True)
df_eu_org_21_27_final.columns

Index(['projectID', 'projectAcronym', 'organisationID', 'vatNumber', 'name',
       'shortName', 'SME', 'activityType', 'street', 'postCode', 'city',
       'country', 'nutsCode', 'geolocation', 'organizationURL', 'contactForm',
       'contentUpdateDate', 'rcn', 'order', 'role', 'ecContribution',
       'netEcContribution', 'totalCostOrg', 'endOfParticipation', 'active',
       'status', 'title', 'startDate', 'endDate', 'totalCostProj', 'topics',
       'fundingScheme', 'grantDoi', 'keywords'],
      dtype='object')

Now we will consolidate both tables, and adding the `period` variable for each:

In [82]:
df_eu_org_14_20_final["period"] = "2014-2020"
df_eu_org_21_27_final["period"] = "2021-2027"

In [83]:
df_eu_consur_db = pd.concat([df_eu_org_14_20_final,df_eu_org_21_27_final],ignore_index=True)

In [84]:
df_eu_consur_db.shape

(83454, 35)

In [85]:
df_eu_consur_db["period"].value_counts()

period
2014-2020    41727
2021-2027    41727
Name: count, dtype: int64

## 2. CLINICAL TRIAL DATASETS

In [75]:
url = "https://clinicaltrials.gov/api/v2/studies"

europe_countries = [
    "Germany", "France", "Switzerland", "United Kingdom", "Spain",
    "Italy", "Netherlands", "Belgium", "Sweden", "Denmark",
    "Austria", "Norway", "Finland", "Ireland", "Poland"
]

rows = []

for country in europe_countries:
    params = {
        "query.cond": "oncology OR genomics OR liquid biopsy",
        "query.locn": country,
        "filter.overallStatus": "RECRUITING,ACTIVE_NOT_RECRUITING,NOT_YET_RECRUITING",
        "pageSize": 100,
        "format": "json"
    }

    response = requests.get(url, params=params)
    response.raise_for_status()
    data = response.json()

    for study in data.get("studies", []):
        protocol = study.get("protocolSection", {})
        identification = protocol.get("identificationModule", {})
        status = protocol.get("statusModule", {})
        design = protocol.get("designModule", {})
        sponsor = protocol.get("sponsorCollaboratorsModule", {})
        conditions = protocol.get("conditionsModule", {})
        dates = status.get("startDateStruct", {})

        rows.append({
            "country_search": country,
            "nct_id": identification.get("nctId"),
            "title": identification.get("briefTitle"),
            "status": status.get("overallStatus"),
            "start_date": dates.get("date"),
            "phase": design.get("phases", []),
            "sponsor": sponsor.get("leadSponsor", {}).get("name"),
            "conditions": conditions.get("conditions", [])
        })

df_trials = pd.DataFrame(rows)

print(df_trials.head())

  country_search       nct_id  \
0        Germany  NCT05668988
1        Germany  NCT06430866
2        Germany  NCT06890273
3        Germany  NCT06645886
4        Germany  NCT05129969

                                               title                 status  \
0  A Study of DZD9008 Versus Platinum-Based Doubl...  ACTIVE_NOT_RECRUITING
1  Pharmacokinetic Similarity Between ABP 234 and...  ACTIVE_NOT_RECRUITING
2  NIS to Examine the Effectiveness and Safety of...             RECRUITING
3  A Study to Investigate the Safety and Efficacy...  ACTIVE_NOT_RECRUITING
4   Registry Platform Ovarian and Endometrial Cancer             RECRUITING

   start_date     phase                   sponsor  \
0  2022-12-13  [PHASE3]     Dizal Pharmaceuticals
1  2024-09-12  [PHASE3]                     Amgen
2  2025-05-20        []               AstraZeneca
3  2024-12-09  [PHASE1]  Kumquat Biosciences Inc.
4  2021-11-25        []               iOMEDICO AG

                                          conditions
0                       [Non-small Cell Lung Cancer]
1  [Early-stage Non-squamous Non-small Cell Lung ...
2                               [Endometrial Cancer]
3                  [Hematologic Malignancies, Adult]
4  [Ovarian Cancer, Endometrial Cancer, Ovary Neo...

In [76]:
df_trials.columns

Index(['country_search', 'nct_id', 'title', 'status', 'start_date', 'phase',
       'sponsor', 'conditions'],
      dtype='object')

In [77]:
df_trials['country_search'].unique()

array(['Germany', 'France', 'Switzerland', 'United Kingdom', 'Spain',
       'Italy', 'Netherlands', 'Belgium', 'Sweden', 'Denmark', 'Austria',
       'Norway', 'Finland', 'Ireland', 'Poland'], dtype=object)

### 3. US INFORMATION

In [78]:
url2="https://api.reporter.nih.gov/v2/projects/search"

payload = {
    "criteria": {
        "advanced_text_search": {
            "operator": "and",
            "search_field": "all",
            "search_text": "genomics OR diagnostics OR oncology"
        },
        "fiscal_years": [2024, 2025]
    },
    "limit": 100,
    "offset": 0
}

response = requests.post(url2, json=payload)
data = response.json()
rows = []

for project in data["results"]:
    org = project.get("organization", {})
    rows.append({
        "project_title": project.get("project_title"),
        "fiscal_year": project.get("fiscal_year"),
        "award_amount": project.get("award_amount"),
        "institution": org.get("org_name"),
        "city": org.get("org_city"),
        "country": org.get("org_country"),
        "abstract": project.get("abstract_text")
    })

df_nih = pd.DataFrame(rows)

print(df_nih.head())

                                       project_title  fiscal_year  \
0                     Developmental Research Program         2025
1  High-Throughput Genomics and Bioinformatic Ana...         2025
2  Matching genotypes with personalized therapies...         2025
3  Commercialization of a rapid, automated Hi-C p...         2025
4  ECOG-ACRIN Integrated Leukemia Translational S...         2025

   award_amount                                        institution  \
0       81247.0                UNIVERSITY OF MICHIGAN AT ANN ARBOR
1      275705.0  UTAH STATE HIGHER EDUCATION SYSTEM--UNIVERSITY...
2      407737.0                           JOHNS HOPKINS UNIVERSITY
3      746680.0                                    CANTATA BIO LLC
4      848075.0                  SLOAN-KETTERING INST CAN RESEARCH

             city        country  \
0       ANN ARBOR  UNITED STATES
1  SALT LAKE CITY  UNITED STATES
2       BALTIMORE  UNITED STATES
3       Worcester  UNITED STATES
4        NEW YORK  UNITED STATES

                                            abstract
0  The Developmental Research Program (DRP) will ...
1  HIGH-THROUGHPUT GENOMICS AND BIOINFORMATIC ANA...
2  Project Summary\nDespite the progress made in ...
3  ABSTRACT\nCancer is projected to affect 20M pe...
4  PROJECT SUMMARY\nThe Leukemia Translational Sc...

In [79]:
df_nih.columns

Index(['project_title', 'fiscal_year', 'award_amount', 'institution', 'city',
       'country', 'abstract'],
      dtype='object')

In [80]:
df_nih['country'].unique()

array(['UNITED STATES'], dtype=object)

In [81]:
df_nih['city'].unique()

array(['ANN ARBOR', 'SALT LAKE CITY', 'BALTIMORE', 'Worcester',
       'NEW YORK', 'DURHAM', 'Columbus', 'NEW ORLEANS', 'STANFORD',
       'PORTLAND', 'SAINT LOUIS', 'OSWEGO', 'LEXINGTON', 'BOSTON',
       'Newark', 'PHILADELPHIA', None, 'ARCADIA', 'ATLANTA', 'SEATTLE',
       'Aurora', 'MEMPHIS', 'ALBUQUERQUE', 'WASHINGTON', 'San Diego',
       'LOS ANGELES', 'DALLAS', 'HOUSTON', 'MILWAUKEE', 'RICHLAND',
       'ROCHESTER', 'MADISON', 'Decatur', 'BURLINGTON', 'SAN FRANCISCO',
       'HONOLULU', 'BAR HARBOR', 'SAN DIEGO', 'MATHER', 'Pasadena',
       'OAKLAND'], dtype=object)